nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['Content-Type', 'Authorization', 'Accept']
        expose_headers: ['Content-Disposition']
        allow_methods: ['GET', 'POST', 'OPTIONS']
        max_age: 3600
