nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000']  # React app URL
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Disposition']
        allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE']
            max_age: 3600
