services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: Symfony
            MYSQL_USER: Symfony
            MYSQL_PASSWORD: Symfony
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - "skeleton_network"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        platform: linux/amd64
        depends_on:
            - db
        ports:
            - "8084:80"
        environment:
            PMA_HOST: db
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
        networks:
            - "skeleton_network"

    php:
        build: .
        depends_on:
            - db
        networks:
            - "skeleton_network"

    app:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
            - "./:/var/www"
        depends_on:
            - php
        networks:
            - "skeleton_network"

networks:
    skeleton_network:
        driver: bridge

volumes:
    db_data: { }
