services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bourse_aux_stages
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - "skeleton_network"

  app:
    build: .
    depends_on:
      - "db"
    volumes:
      - "./:/app"
    networks:
      - "skeleton_network"

  phpmyadmin:
    image: phpmyadmin:latest
    volumes:
      - "./:/app"
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      UPLOAD_LIMIT: 512M
      MAX_EXECUTION_TIME: 300
    networks:
      - "skeleton_network"

networks:
  skeleton_network:
    driver: bridge
