services:
  ssh-agent:
    image: nardeas/ssh-agent:latest
    volumes:
      - "~/mw-ssh:/root/.ssh:ro"
    environment:
      - SSH_AUTH_SOCK=/.ssh-agent/socket


  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bourse_aux_stages

  app:
    ports:
      - "80:80"
      - "443:443"
    build:
      context: ./
      dockerfile: Dockerfile
      network: host
    volumes:
      - "./:/app"
      - "~/mw-ssh:/root/.ssh:ro"
    environment:
      - SSH_AUTH_SOCK=/.ssh-agent/socket
    restart: always
    depends_on:
      - "db"

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      UPLOAD_LIMIT: 512M
      MAX_EXECUTION_TIME: 300
